spring.datasource.url=jdbc:mysql://mysql-3223faf4-mkpratyu2006-bb90.l.aivencloud.com:28905/defaultdb?ssl-mode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_zVHoeXNBHlRh1NYXARV

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

server.port=8081