spring.datasource.url=mysql://avnadmin:AVNS_zVHoeXNBHlRh1NYXARV@mysql-3223faf4-mkpratyu2006-bb90.l.aivencloud.com:28905/defaultdb?ssl-mode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=YOUR_PASSWORD
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

server.port=8081